[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# Compiler settings
solc_version = "0.8.30"
optimizer = true
optimizer_runs = 200
via_ir = false

# Gas reporting
gas_reports = ["CryptoHeir"]
gas_reports_ignore = []

# Testing
fuzz = { runs = 256, max_test_rejects = 65536 }
invariant = { runs = 256, depth = 500, fail_on_revert = false }

# Code coverage
verbosity = 2

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[profile.ci]
fuzz = { runs = 10000 }
invariant = { runs = 1000, depth = 1000 }
